package cl.komatsu.soap.simularcrearcliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.2
 * 2023-10-20T12:55:39.020-03:00
 * Generated source version: 3.5.2
 *
 */
@WebService(targetNamespace = "http://simularcrearcliente.soap.komatsu.cl", name = "SimularCrearClientePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface SimularCrearClientePortType {

    @WebMethod(operationName = "SimularCrearCliente", action = "urn:SimularCrearCliente")
    @Action(input = "urn:SimularCrearCliente", output = "urn:SimularCrearClienteResponse")
    @RequestWrapper(localName = "SimularCrearCliente", targetNamespace = "http://simularcrearcliente.soap.komatsu.cl", className = "cl.komatsu.soap.simularcrearcliente.SimularCrearCliente")
    @ResponseWrapper(localName = "SimularCrearClienteResponse", targetNamespace = "http://simularcrearcliente.soap.komatsu.cl", className = "cl.komatsu.soap.simularcrearcliente.SimularCrearClienteResponse")
    public void simularCrearCliente(

        @WebParam(name = "I_KNA1", targetNamespace = "http://simularcrearcliente.soap.komatsu.cl")
        cl.komatsu.soap.simularcrearcliente.IKna1Type iKNA1,
        @WebParam(name = "I_KNVV", targetNamespace = "http://simularcrearcliente.soap.komatsu.cl")
        cl.komatsu.soap.simularcrearcliente.IKnvvType iKNVV,
        @WebParam(name = "I_BUKRS", targetNamespace = "http://simularcrearcliente.soap.komatsu.cl")
        java.lang.String iBUKRS,
        @WebParam(name = "I_AKONT", targetNamespace = "http://simularcrearcliente.soap.komatsu.cl")
        java.lang.String iAKONT,
        @WebParam(name = "I_ZUAWA", targetNamespace = "http://simularcrearcliente.soap.komatsu.cl")
        java.lang.String iZUAWA,
        @WebParam(name = "I_FDGRV", targetNamespace = "http://simularcrearcliente.soap.komatsu.cl")
        java.lang.String iFDGRV,
        @WebParam(name = "I_ZTERM", targetNamespace = "http://simularcrearcliente.soap.komatsu.cl")
        java.lang.String iZTERM,
        @WebParam(name = "I_BZIRK", targetNamespace = "http://simularcrearcliente.soap.komatsu.cl")
        java.lang.String iBZIRK,
        @WebParam(name = "I_WAERS", targetNamespace = "http://simularcrearcliente.soap.komatsu.cl")
        java.lang.String iWAERS,
        @WebParam(name = "I_VSBED", targetNamespace = "http://simularcrearcliente.soap.komatsu.cl")
        java.lang.String iVSBED,
        @WebParam(name = "I_KTGRD", targetNamespace = "http://simularcrearcliente.soap.komatsu.cl")
        java.lang.String iKTGRD,
        @WebParam(name = "GT_ADRS12", targetNamespace = "http://simularcrearcliente.soap.komatsu.cl")
        cl.komatsu.soap.simularcrearcliente.GtAdr12Type gtADRS12,
        @WebParam(name = "GT_ADRS6", targetNamespace = "http://simularcrearcliente.soap.komatsu.cl")
        cl.komatsu.soap.simularcrearcliente.GtAdr6Type gtADRS6,
        @WebParam(mode = WebParam.Mode.OUT, name = "GT_RETURNS", targetNamespace = "http://simularcrearcliente.soap.komatsu.cl")
        javax.xml.ws.Holder<GtReturnType> gtRETURNS,
        @WebParam(mode = WebParam.Mode.OUT, name = "E_KUNNR", targetNamespace = "http://simularcrearcliente.soap.komatsu.cl")
        javax.xml.ws.Holder<java.lang.String> eKUNNR
    );
}
