package cl.komatsu.soap.crearcliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.2
 * 2023-10-20T12:55:38.480-03:00
 * Generated source version: 3.5.2
 *
 */
@WebService(targetNamespace = "http://crearcliente.soap.komatsu.cl", name = "CrearClientePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface CrearClientePortType {

    @WebMethod(operationName = "CrearCliente", action = "urn:CrearCliente")
    @Action(input = "urn:CrearCliente", output = "urn:CrearClienteResponse")
    @RequestWrapper(localName = "CrearCliente", targetNamespace = "http://crearcliente.soap.komatsu.cl", className = "cl.komatsu.soap.crearcliente.CrearCliente")
    @ResponseWrapper(localName = "CrearClienteResponse", targetNamespace = "http://crearcliente.soap.komatsu.cl", className = "cl.komatsu.soap.crearcliente.CrearClienteResponse")
    public void crearCliente(

        @WebParam(name = "I_KNA1", targetNamespace = "http://crearcliente.soap.komatsu.cl")
        cl.komatsu.soap.crearcliente.IKna1Type iKNA1,
        @WebParam(name = "I_KNVV", targetNamespace = "http://crearcliente.soap.komatsu.cl")
        cl.komatsu.soap.crearcliente.IKnvvType iKNVV,
        @WebParam(name = "I_BUKRS", targetNamespace = "http://crearcliente.soap.komatsu.cl")
        java.lang.String iBUKRS,
        @WebParam(name = "I_AKONT", targetNamespace = "http://crearcliente.soap.komatsu.cl")
        java.lang.String iAKONT,
        @WebParam(name = "I_ZUAWA", targetNamespace = "http://crearcliente.soap.komatsu.cl")
        java.lang.String iZUAWA,
        @WebParam(name = "I_FDGRV", targetNamespace = "http://crearcliente.soap.komatsu.cl")
        java.lang.String iFDGRV,
        @WebParam(name = "I_ZTERM", targetNamespace = "http://crearcliente.soap.komatsu.cl")
        java.lang.String iZTERM,
        @WebParam(name = "I_BZIRK", targetNamespace = "http://crearcliente.soap.komatsu.cl")
        java.lang.String iBZIRK,
        @WebParam(name = "I_WAERS", targetNamespace = "http://crearcliente.soap.komatsu.cl")
        java.lang.String iWAERS,
        @WebParam(name = "I_VSBED", targetNamespace = "http://crearcliente.soap.komatsu.cl")
        java.lang.String iVSBED,
        @WebParam(name = "I_KTGRD", targetNamespace = "http://crearcliente.soap.komatsu.cl")
        java.lang.String iKTGRD,
        @WebParam(name = "GT_ADRS12", targetNamespace = "http://crearcliente.soap.komatsu.cl")
        cl.komatsu.soap.crearcliente.GtAdr12Type gtADRS12,
        @WebParam(name = "GT_ADRS6", targetNamespace = "http://crearcliente.soap.komatsu.cl")
        cl.komatsu.soap.crearcliente.GtAdr6Type gtADRS6,
        @WebParam(mode = WebParam.Mode.OUT, name = "GT_RETURNS", targetNamespace = "http://crearcliente.soap.komatsu.cl")
        javax.xml.ws.Holder<GtReturnType> gtRETURNS,
        @WebParam(mode = WebParam.Mode.OUT, name = "E_KUNNR", targetNamespace = "http://crearcliente.soap.komatsu.cl")
        javax.xml.ws.Holder<java.lang.String> eKUNNR
    );
}
