package cl.komatsu.consultarcliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.2
 * 2023-10-19T09:50:37.600-03:00
 * Generated source version: 3.5.2
 *
 */
@WebService(targetNamespace = "http://consultarcliente.komatsu.cl", name = "ConsultarClientePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ConsultarClientePortType {

    @WebMethod(operationName = "ConsultarCliente", action = "urn:ConsultarCliente")
    @Action(input = "urn:ConsultarCliente", output = "urn:ConsultarClienteResponse")
    @RequestWrapper(localName = "ConsultarCliente", targetNamespace = "http://consultarcliente.komatsu.cl", className = "cl.komatsu.consultarcliente.ConsultarCliente")
    @ResponseWrapper(localName = "ConsultarClienteResponse", targetNamespace = "http://consultarcliente.komatsu.cl", className = "cl.komatsu.consultarcliente.ConsultarClienteResponse")
    public void consultarCliente(

        @WebParam(name = "I_KUNNR", targetNamespace = "http://consultarcliente.komatsu.cl")
        java.lang.String iKUNNR,
        @WebParam(name = "I_BUKRS", targetNamespace = "http://consultarcliente.komatsu.cl")
        java.lang.String iBUKRS,
        @WebParam(mode = WebParam.Mode.OUT, name = "GT_RETURNS", targetNamespace = "http://consultarcliente.komatsu.cl")
        javax.xml.ws.Holder<GtReturnType> gtRETURNS,
        @WebParam(mode = WebParam.Mode.OUT, name = "E_KNA1", targetNamespace = "http://consultarcliente.komatsu.cl")
        javax.xml.ws.Holder<EKnaType> eKNA1,
        @WebParam(mode = WebParam.Mode.OUT, name = "GT_ADRS12", targetNamespace = "http://consultarcliente.komatsu.cl")
        javax.xml.ws.Holder<GtAdr12Type> gtADRS12,
        @WebParam(mode = WebParam.Mode.OUT, name = "GT_ADRS6", targetNamespace = "http://consultarcliente.komatsu.cl")
        javax.xml.ws.Holder<GtAdr6Type> gtADRS6,
        @WebParam(mode = WebParam.Mode.OUT, name = "GT_KNVVS", targetNamespace = "http://consultarcliente.komatsu.cl")
        javax.xml.ws.Holder<GtKnvvs> gtKNVVS
    );
}
