package cl.komatsu.consultarcliente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.2
 * 2023-10-19T09:50:37.663-03:00
 * Generated source version: 3.5.2
 *
 */
@WebServiceClient(name = "ConsultarCliente",
                  wsdlLocation = "file:/C:/komatsu-proyectos/FUSE-Migraciones/02-%20Integraciones%20CRM/KCC-Migracion-Integraciones-Fuse-CRM-Cliente/src/main/resources/static/wsdl/consultar_clicrm.wsdl",
                  targetNamespace = "http://consultarcliente.komatsu.cl")
public class ConsultarCliente_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://consultarcliente.komatsu.cl", "ConsultarCliente");
    public final static QName ConsultarClienteSoapEndpoint = new QName("http://consultarcliente.komatsu.cl", "ConsultarClienteSoapEndpoint");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/komatsu-proyectos/FUSE-Migraciones/02-%20Integraciones%20CRM/KCC-Migracion-Integraciones-Fuse-CRM-Cliente/src/main/resources/static/wsdl/consultar_clicrm.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ConsultarCliente_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/komatsu-proyectos/FUSE-Migraciones/02-%20Integraciones%20CRM/KCC-Migracion-Integraciones-Fuse-CRM-Cliente/src/main/resources/static/wsdl/consultar_clicrm.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ConsultarCliente_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ConsultarCliente_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultarCliente_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ConsultarCliente_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ConsultarCliente_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ConsultarCliente_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ConsultarClientePortType
     */
    @WebEndpoint(name = "ConsultarClienteSoapEndpoint")
    public ConsultarClientePortType getConsultarClienteSoapEndpoint() {
        return super.getPort(ConsultarClienteSoapEndpoint, ConsultarClientePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultarClientePortType
     */
    @WebEndpoint(name = "ConsultarClienteSoapEndpoint")
    public ConsultarClientePortType getConsultarClienteSoapEndpoint(WebServiceFeature... features) {
        return super.getPort(ConsultarClienteSoapEndpoint, ConsultarClientePortType.class, features);
    }

}
